In [1]:
import numpy as np
from random import randint

In [2]:
vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=int)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
matrix = np.array([[0,0,0],[0,0,0],[0,0,0]], dtype=int)
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [4]:
matrix2= np.array([[randint(1,10) for _ in range(5)] for _ in range(5)])
print(matrix2)

[[ 3  1 10  6  3]
 [ 3  2  5  4  8]
 [ 9  5  2  4  9]
 [ 4  7  7  5 10]
 [10 10  1  2  1]]


In [5]:
matrix3 = np.random.random((4,4))
print(matrix3)

[[0.06401179 0.97781995 0.7936729  0.25355697]
 [0.28598655 0.1358653  0.39399675 0.38868123]
 [0.87467736 0.97014    0.32723265 0.29067574]
 [0.31371461 0.41585521 0.2517523  0.44376557]]


In [6]:
vec1 = np.array([[1,2,3,4,5]], dtype=int)
vec2 = np.array([[6,7,8,9,10]], dtype=int)
print(vec2-vec1)
print(vec2+vec1)
print(vec2*vec1)

[[5 5 5 5 5]]
[[ 7  9 11 13 15]]
[[ 6 14 24 36 50]]


In [7]:
a = np.array([randint(1,10) for _ in range(7)])
b = np.array([randint(1,10) for _ in range(7)])
print(f'num 6 = {np.dot(a, b)}')

num 6 = 262


In [8]:
first = np.array([[randint(1,10) for _ in range(2)] for _ in range(2)])
second = np.array([[randint(1,10) for _ in range(3)] for _ in range(2)])
res = np.dot(first,second)
print(res)

[[ 36  26  18]
 [144  94 102]]


In [9]:
numb8 = np.array([[randint(1,10) for _ in range(3)] for _ in range(3)])
a_inv = np.linalg.inv(numb8)
print(a_inv)

[[ 0.80769231 -0.23076923 -0.03846154]
 [ 0.23076923  0.07692308 -0.15384615]
 [-0.65384615  0.11538462  0.26923077]]


In [10]:
numb9 = np.random.random((4,4))
result9 = numb9.T
print(result9)

[[0.63740068 0.9509082  0.09060884 0.12682921]
 [0.35818025 0.82170797 0.88084707 0.66109339]
 [0.32570885 0.5590296  0.25936043 0.86454663]
 [0.63390607 0.11275658 0.11118502 0.736394  ]]


In [11]:
numb10 = np.array([[randint(1,10) for _ in range(4)] for _ in range(3)])
vec10 = np.array([0,4,5,9])
print(np.dot(numb10,vec10))

[131 119 110]


In [12]:
mat11 = np.random.random((2,3))
vec11 = np.random.random((3,))
print(np.dot(mat11,vec11))

[0.8543645  0.63030021]


In [13]:
mat_1 = np.random.randint(1,10,(2,2))
mat_2 = np.random.randint(1,10,(2,2))
print(f' This is mat_1{mat_1}\n this is mat_2 = {mat_2}')
print(mat_2*mat_1)

 This is mat_1[[8 5]
 [5 7]]
 this is mat_2 = [[5 7]
 [8 7]]
[[40 35]
 [40 49]]


In [14]:
mat_1 = np.random.randint(1,10,(2,2))
mat_2 = np.random.randint(1,10,(2,2))
print(np.prod(mat_2))
print(np.prod(mat_1))

840
90


In [15]:
mat_14 = np.random.randint(1,100,(5,5))
print(np.sum(mat_14))

1370


In [16]:
mat_15 = np.random.randint(1,10,(4,4))
mat_152 = np.random.randint(1,10,(4,4))
print(mat_15 - mat_152)

[[ 0  4 -3  4]
 [ 3 -3  4  4]
 [ 6 -4  3  0]
 [-7  2  3  1]]


In [17]:
matrix = np.random.random((3, 3))
print(np.sum(matrix,axis=1))

[1.64375582 1.6028615  1.38424475]


In [18]:
matrix = np.random.randint(1,10,(3,4))
print(matrix**2)

[[ 1  1 81 49]
 [ 4 16 36 36]
 [25 16 36 49]]


In [19]:
v = np.array([1,81,36,9])
print(np.sqrt(v))

[1. 9. 6. 3.]
